# Generated by Django 4.2.1 on 2023-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_image', models.ImageField(blank=True, upload_to='images/messages/', verbose_name='Изображение')),
                ('message_time', models.DateTimeField(verbose_name='Время отправления')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sender_visibility', models.BooleanField(default=True, verbose_name='Отображение у отправителя')),
                ('receiver_visibility', models.BooleanField(default=True, verbose_name='Отображение у получателя')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
