# Generated by Django 4.2.1 on 2023-12-16 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='saleman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleman_comment', to=settings.AUTH_USER_MODEL, verbose_name='Ответ продавца'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор'),
        ),
        migrations.AddField(
            model_name='product_сurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category_сurrency', verbose_name='Категория валюты'),
        ),
        migrations.AddField(
            model_name='product_сurrency',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='product_сurrency',
            name='platform_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.platform_currency', verbose_name='Платформа валюты'),
        ),
        migrations.AddField(
            model_name='product_сurrency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.platform', verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='platform_currency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category_сurrency', verbose_name='Категория валюты'),
        ),
        migrations.AddField(
            model_name='platform',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='game',
            name='category_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category_game', verbose_name='Категория игры'),
        ),
        migrations.AddField(
            model_name='deal_currency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category_сurrency', verbose_name='Категория валюты'),
        ),
        migrations.AddField(
            model_name='deal_currency',
            name='saleman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleman_currency', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='deal_currency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_currency', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='deal',
            name='saleman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleman', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='category_сurrency',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='category',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
